#!/usr/bin/env python3

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import re
import shutil
import sys

GENERATED_HEADER = [
    "# Generated by ~/.dotfiles/automation/codex/install-codex.sh.",
    "# Edit shared settings in ~/.dotfiles/config/codex/config.toml.",
    "# Optional machine-local additive settings belong in ~/.codex/config.local.toml.",
    "# Machine-local trust entries belong in ~/.codex/projects.local.toml.",
]
GENERATED_FOOTER = [
    "# New [projects.\"...\"] trust entries written here by Codex should be moved to",
    "# ~/.codex/projects.local.toml. Rerun ~/.dotfiles/automation/codex/install-codex.sh",
    "# to sync and clean them up.",
]


PROJECTS_TABLE_RE = re.compile(r"^\[projects(?:\]|\.)")
PROJECTS_ENTRY_RE = re.compile(r"^\[projects\.")


def read_text(path: Path) -> str:
    return path.read_text()


def reject_projects_table(path: Path, text: str) -> None:
    for line in text.splitlines():
        if PROJECTS_TABLE_RE.match(line.strip()):
            raise SystemExit(
                f"{path} must not define [projects]; use ~/.codex/projects.local.toml instead"
            )


def extract_projects_tables(text: str) -> str:
    extracted: list[str] = []
    current_block: list[str] = []
    in_projects = False

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if line.startswith("["):
            if PROJECTS_ENTRY_RE.match(line):
                if current_block:
                    extracted.extend(current_block)
                    if current_block[-1] != "":
                        extracted.append("")
                current_block = [raw_line]
                in_projects = True
                continue

            if in_projects:
                extracted.extend(current_block)
                if current_block and current_block[-1] != "":
                    extracted.append("")
                current_block = []
                in_projects = False

        if in_projects:
            if line.startswith("#"):
                continue
            current_block.append(raw_line)

    if current_block:
        extracted.extend(current_block)
        if current_block[-1] != "":
            extracted.append("")

    if not extracted:
        return ""

    header = [
        "# Local machine trust state for Codex projects.",
        "# This file is updated by ~/.dotfiles/automation/codex/install-codex.sh.",
        "# Do not move these entries into the tracked dotfiles config.",
        "",
    ]
    return "\n".join(header + extracted).rstrip() + "\n"


def sync_projects_from_target(target: Path, projects_path: Path) -> None:
    if not target.exists():
        return

    projects_text = extract_projects_tables(read_text(target))
    if not projects_text:
        return

    projects_path.parent.mkdir(parents=True, exist_ok=True)
    projects_path.write_text(projects_text)
    print(f"Synced project trust entries to {projects_path}")


def build_rendered_config(shared: Path, local: Path, projects: Path) -> str:
    shared_text = read_text(shared)
    reject_projects_table(shared, shared_text)

    parts = [*GENERATED_HEADER, "", shared_text.strip()]

    if local.exists():
        local_text = read_text(local)
        reject_projects_table(local, local_text)
        stripped = local_text.strip()
        if stripped:
            parts.extend(["", stripped])

    if projects.exists():
        projects_text = read_text(projects)
        stripped = projects_text.strip()
        if stripped:
            parts.extend(["", stripped])

    parts.extend(["", *GENERATED_FOOTER])
    return "\n".join(parts).rstrip() + "\n"


def backup_if_needed(target: Path) -> None:
    if target.is_symlink():
        target.unlink()
        print(f"Replaced symlinked {target} with a rendered config file")
        return

    if not target.exists():
        return

    current_text = target.read_text()
    if current_text.startswith(GENERATED_HEADER[0]):
        return

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    backup = target.with_name(f"{target.name}.bak.{timestamp}")
    shutil.move(target, backup)
    print(f"Backed up {target} to {backup}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--shared", required=True, type=Path)
    parser.add_argument("--local", required=True, type=Path)
    parser.add_argument("--projects", required=True, type=Path)
    parser.add_argument("--target", required=True, type=Path)
    args = parser.parse_args()

    if not args.shared.exists():
        raise SystemExit(f"missing shared config: {args.shared}")

    sync_projects_from_target(args.target, args.projects)
    rendered = build_rendered_config(args.shared, args.local, args.projects)

    args.target.parent.mkdir(parents=True, exist_ok=True)
    backup_if_needed(args.target)
    args.target.write_text(rendered)
    print(f"Rendered {args.target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
